# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-app
  template:
    metadata:
      labels:
        app: sre-app
    spec:
      containers:
      - name: sre-app
        image: sre-app:latest
        ports:
        - containerPort: 6666
---
apiVersion: v1
kind: Service
metadata:
  name: sre-app
spec:
  type: NodePort
  selector:
    app: sre-app
  ports:
    - protocol: TCP
      port: 6666
      targetPort: 6666
